# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d374416cd4c7887567694e36f137d2148a98ddc1fe58920d115dddce08fe1f72621d70a510139d707f94e15fce145f9b63f305b25ad3bfc3294d3b81dbff3537

test:
  secret_key_base: af9c8a3cf9154e4fc710b3f09b4afcfa03ca2e35bae3a2a173dda5e1080eb69e8e23a0999e19e903453c8a47c607224292944a3d6dd50b7485c59860bf39989d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
